/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalatySetting.java
 *
 * Created on 2013-6-20, 13:09:57
 */

package rabbit;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SalarySetting extends javax.swing.JFrame {

    /** Creates new form SalatySetting */
     private Toolkit tk = Toolkit.getDefaultToolkit();
    int x = tk.getScreenSize().width / 2 - 200;
    int y = tk.getScreenSize().height / 2 - 200;
    public SalarySetting() {
        initComponents();
        setTitle("工资设定");
        setLocation(x,y);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        basepayTextField = new javax.swing.JTextField();
        welfareTextField = new javax.swing.JTextField();
        rewarkTextField = new javax.swing.JTextField();
        insuranceTextField = new javax.swing.JTextField();
        fundTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        remarkTextField = new javax.swing.JTextField();
        monthCMB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("员工工资"));

        jLabel1.setText("员工号:");

        jLabel2.setText("基本工资：");

        jLabel3.setText("福利补贴:");

        jLabel4.setText("奖励工资:");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("失业保险:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("住房公积金:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("月份:");

        basepayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basepayTextFieldActionPerformed(evt);
            }
        });

        welfareTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welfareTextFieldActionPerformed(evt);
            }
        });

        rewarkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rewarkTextFieldActionPerformed(evt);
            }
        });

        insuranceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceTextFieldActionPerformed(evt);
            }
        });

        fundTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("保存设定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取消设定");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("*基本工资不能超过3000元");

        jLabel11.setText("备注:");

        remarkTextField.setText("未结算");

        monthCMB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remarkTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(idTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(basepayTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(welfareTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rewarkTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insuranceTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(basepayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(welfareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rewarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(insuranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(monthCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(remarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DBConn db;
        String ID = this.idTextField.getText(); //员工号
        int basepay = Integer.parseInt(this.basepayTextField.getText());  //基本工资
        int welfare = Integer.parseInt(this.welfareTextField.getText());   //福利工资
        int reward = Integer.parseInt(rewarkTextField.getText());   //奖励工资
        int insurance = Integer.parseInt(this.insuranceTextField.getText());//失业保险
        int funds = Integer.parseInt(this.fundTextField.getText());//////住房公积金
        String month = (String) this.monthCMB.getSelectedItem();
        String remark = this.remarkTextField.getText();
       
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null, "员工号不能为空！！");
        }else if(basepay > 3000 || basepay < 0){
            JOptionPane.showMessageDialog(null, "基本工资不能超过3000元！！！");
            this.basepayTextField.setText("");
        }else{
             try {
                 db = new DBConn();
                 
               String checkid = "select ID from employee where ID = '"+ ID +"'";
                String sql0 = "select  name ,department, position from employee where ID = '"+ ID +"'";
                 String sql2 = "select  ID ,month from salary where ID = '"+ ID +"'";
                 //String name= "select name from employee where ID = '"+ ID +"'";
                // String department= "select department from employee where ID = '"+ ID +"'";
                // String position= "select position from employee where ID = '"+ ID +"'";
                ResultSet rs = db.Search(sql0);
                    
                String name = "";
                String department="";
                String position = "";
                while(rs.next())
                {
                    name = rs.getString("Name");
                    department = rs.getString("department");
                    position = rs.getString("position");
                }
                   System.out.println(name);
                   System.out.println(department);
                   System.out.println(position);
                   
                    ResultSet rs1 = db.Search(sql2);
                   String id1= "";
                   String month1="";
                   while(rs1.next())
                {
                    id1 = rs1.getString("ID");
                    month1 = rs1.getString("month");
                   
                }
                   System.out.println(id1);
                   System.out.println(month1);
                    System.out.println(ID);
                    System.out.println(month);
                  /*String name= rs.getString("name");
                  String department=rs.getString("department");
                  String position=rs.getString("position");*/
                   
                   //System.out.println(name);
                  // System.out.println(department);
                  // System.out.println(position);
                 //检查是否有该员工
                 if(db.Check(checkid) == 0||(ID.equals(id1)&&month.equals(month1))){
                     JOptionPane.showMessageDialog(null, "没有该员工信息或该信息已录入！！！");
                     idTextField.setText("");
                 }else{
                     System.out.println(checkid);
                     String sql = "insert into salary(ID,name,basepay,welfare,reward,insurance,funds,month,remark) values ('" + ID +"','"+name+"','"+basepay+"','"+welfare+"','"+reward+"','"+insurance+"','"+funds+"','"+month+"','"+remark+"')";
                      int 总工资=basepay+welfare+reward-insurance-funds;
                     String sql1 = "insert into view_salary(工号,姓名,部门,职位,总工资,月份,备注) values ('" + ID +"','"+name+"','"+department+"','"+position+"','"+总工资+"','"+month+"','"+remark+"')";
                     System.out.println(sql);
                     System.out.println(sql1);
                  
                     if(db.Update(sql) != 0&&db.Update(sql1) != 0){
                         JOptionPane.showMessageDialog(null, "保存成功！！！");
                         idTextField.setText("");
                        basepayTextField.setText("");
                        welfareTextField.setText("");
                       rewarkTextField. setText("");
                       insuranceTextField. setText("");
                        fundTextField.setText("");
                     }else{
                         JOptionPane.showMessageDialog(null, "保存失败！！");
                     }
                 }
                 
                 db.close();
             } catch (SQLException ex) {
                 Logger.getLogger(SalarySetting.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        idTextField.setText("");
        basepayTextField.setText("");
        welfareTextField.setText("");
       rewarkTextField. setText("");
       insuranceTextField. setText("");
        fundTextField.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void basepayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basepayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basepayTextFieldActionPerformed

    private void welfareTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welfareTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_welfareTextFieldActionPerformed

    private void rewarkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rewarkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rewarkTextFieldActionPerformed

    private void insuranceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceTextFieldActionPerformed

    private void fundTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fundTextFieldActionPerformed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalarySetting().setVisible(true);
            }
        });
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basepayTextField;
    private javax.swing.JTextField fundTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField insuranceTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox monthCMB;
    private javax.swing.JTextField remarkTextField;
    private javax.swing.JTextField rewarkTextField;
    private javax.swing.JTextField welfareTextField;
    // End of variables declaration//GEN-END:variables

}
