/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Statistics.java
 *
 * Created on 2013-6-23, 14:14:39
 */

package rabbit;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Statistics extends javax.swing.JFrame {

    /** Creates new form Statistics */
    private Toolkit tk = Toolkit.getDefaultToolkit();
    int x = tk.getScreenSize().width / 2 - 180;
    int y = tk.getScreenSize().height / 2 - 180;

    DefaultComboBoxModel dcm;

    String[] head = {"部门", "负责人", "总人数", "总工资"};
    Object[][] obj = new Object[0][0];
    DefaultTableModel dtm = new DefaultTableModel(obj, head);

    public Statistics() {
        initComboBox();
        initComponents();
        setTitle("信息统计");
        setLocation(x,y);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }


      ///初始化下拉列表
    private void initComboBox(){
        Vector v = new Vector();
        DBConn db = new DBConn();
        try{
            ResultSet rs = db.Search("select distinct name from department");
            while(rs.next()){
                v.addElement(rs.getString("name")); //添加到向量尾部，大小加1
            }
           dcm = new DefaultComboBoxModel(v);
        }catch(SQLException ex){
            ex.printStackTrace();
        }finally{
            db.close();
        }
    }


    private void initTable(String sql){
        try {
         //   String[] head = {"部门", "负责人", "总人数", "总工资"};
        //    Object[][] obj = new Object[0][0];
            dtm = new DefaultTableModel(obj, head);
            Vector v;
            DBConn db = new DBConn();
            ResultSet rs = db.Search(sql);
            while (rs.next()) {
                v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                dtm.addRow(v);
                jTable1.setModel(dtm);
            }
            db.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jname = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jseason = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jname.setModel(dcm);

        jLabel1.setText("部门名称:");

        jLabel2.setText("季度:");

        jseason.setModel(new DefaultComboBoxModel(new String[] { "--请选择季度--", "第一季度", "第二季度", "第三季度", "第四季度" }));

        jButton1.setText("查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(jseason, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jname, 0, 190, Short.MAX_VALUE)
                                .addGap(189, 189, 189))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = (String) jname.getSelectedItem();
        int index = jseason.getSelectedIndex();
        String sql = null;
        if(index == 1){
            sql = "select 部门,director,number,sum(总工资) from view_salary,department where " +
                    "department.name=部门 and 月份 in ('1月','2月','3月') and 部门='"+ name +"' group by 部门,director,number ";
            System.out.println(sql);
        }else if(index == 2){
            sql = "select 部门,director,number,sum(总工资) from view_salary,department where " +
                    "department.name=部门 and 月份 in ('4月','5月','6月') and 部门='"+ name +"' group by 部门,director,number ";
            System.out.println(sql);
        }else if(index == 3){
            sql = "select 部门,director,number,sum(总工资) from view_salary,department where " +
                    "department.name=部门 and 月份 in ('7月','8月','9月') and 部门='"+ name +"' group by 部门,director,number ";
            System.out.println(sql);
        }else if(index == 4){
            sql = "select 部门,director,number,sum(总工资) from view_salary,department where " +
                    "department.name=部门 and 月份 in ('10月','11月','12月') and 部门='"+ name +"' group by 部门,director,number ";
            System.out.println(sql);
        }else{
            JOptionPane.showMessageDialog(null, "请选择季度");
        }
        initTable(sql);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jname;
    private javax.swing.JComboBox jseason;
    // End of variables declaration//GEN-END:variables

}
